- name: "Checking if Gnome extension is already installed: {{ gnome_extension_id }}"
  stat:
    path: "{{ gnome_extensions['storage']['install'] }}/{{ gnome_extension_id }}.zip"
  register: gnome_extension

- name: "Install Gnome extension: {{ gnome_extension_id }}"
  when: gnome_extension.stat.exists == False
  block:
    - name: "Get Gnome extensions metadata: {{ gnome_extension_id }}"
      uri:
        url: "https://extensions.gnome.org/extension-info/?shell_version={{ gnome_version.stdout }}&pk={{ gnome_extension_id }}"
        return_content: yes
      register: metadata

    - name: "Download Gnome extension ({{ metadata.json.pk }}: {{ metadata.json.name }})"
      get_url:
        url: "https://extensions.gnome.org{{ metadata.json.download_url }}"
        dest: "{{ gnome_extensions['storage']['install'] }}/installing_{{ metadata.json.pk }}.zip"

    - name: "Install Gnome extension ({{ metadata.json.pk }}: {{ metadata.json.name }})"
      become: true
      become_user: "{{ primary_username }}"
      command: "gnome-extensions install --force '{{ gnome_extensions['storage']['install'] }}/installing_{{ metadata.json.pk }}.zip'"

    # TODO: Investigate why gnome extensions arent enabled via ansible
    - name: "Enable Gnome extension ({{ metadata.json.pk }}: {{ metadata.json.name }})"
      become: true
      become_user: "{{ primary_username }}"
      command: "gnome-extensions enable '{{ metadata.json.uuid }}'"

    - name: "Record Installed extension ({{ metadata.json.pk }}: {{ metadata.json.name }})"
      command: mv '{{ gnome_extensions['storage']['install'] }}/installing_{{ metadata.json.pk }}.zip' '{{ gnome_extensions['storage']['install'] }}/{{ metadata.json.pk }}.zip'
