- name: Create Gnome extension install folders
  file:
    state: directory
    path: "{{ gnome_extensions['storage']['install'] }}/"
    owner: root
    group: root

- name: Get Gnome version
  shell: gnome-shell --version | grep -o '[0-9.]*$'
  changed_when: false
  register: gnome_version

- name: Install extensions
  include_tasks: install.yml
  loop: "{{ gnome_extensions['ids'] }}"
  loop_control:
    loop_var: gnome_extension_id

- import_tasks: config/main.yml
  become: true
  become_user: "{{ primary_username }}"
