- name: Install the Atom yum repository key
  rpm_key:
    state: present
    key: https://packagecloud.io/AtomEditor/atom/gpgkey

- name: Install the Atom yum repository
  yum_repository:
    name: atom
    description: Atoms Repo
    baseurl: 'https://packagecloud.io/AtomEditor/atom/el/7/$basearch'
    gpgcheck: no
    repo_gpgcheck: yes
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
