#!/usr/bin/env bash
set -euo pipefail

GIT_FOLDER=~/git
REPO=https://github.com/ZeePal/workstation-amazonlinux2.git
REPO_NAME="$(basename -s .git "$REPO")"


sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install -y ansible git python3

if [[ ! -e $GIT_FOLDER ]]; then
  mkdir -p "$GIT_FOLDER"
fi
cd "$GIT_FOLDER"
git clone "$REPO"

cd "$REPO_NAME"

# Patch to fix usernames with backslashs not being quoted by ansible
sudo patch --forward /usr/lib/python2.7/site-packages/ansible/plugins/become/su.py < ansible_become_su.py.patch

exec ./install
