#!/usr/bin/env bash
set -euo pipefail

GIT_FOLDER=~/git
REPO=/mnt/test
REPO_NAME="$(basename -s .git "$REPO")"


sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install -y ansible git

if [[ ! -e $GIT_FOLDER ]]; then
  mkdir -p "$GIT_FOLDER"
fi
cd "$GIT_FOLDER"
rsync -a "$REPO/" "$GIT_FOLDER/$REPO_NAME/"

cd "$REPO_NAME"
exec ./install
