#!/usr/bin/env bash

# TODO: fix code to not assume home folders, below is a workaround
sudo ln -s "$HOME" "/home/$USER"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
sudo "$SCRIPT_DIR/run_ansible_roles_in_parallel" -u "$USER" "$@"
