- name: Set chrome as default browser
  command: xdg-settings set default-web-browser google-chrome.desktop

- name: Prevent media insertion from auto running
  dconf:
    key: /org/gnome/desktop/media-handling/autorun-never
    value: 'true'

- name: Always show battery percentage
  dconf:
    key: /org/gnome/desktop/interface/show-battery-percentage
    value: 'true'
