- name: Checking if AWS cli is already installed
  stat:
    path: /usr/local/bin/aws
  register: aws_cli_binary

- name: Install AWS CLI
  when: aws_cli_binary.stat.exists == False
  block:
    - name: Create AWS cli install folders
      file:
        state: directory
        path: "{{ awscli['storage']['prefix'] }}/"
        owner: root
        group: root

    - name: Download AWS cli gpg key
      shell: "curl '{{ awscli['gpg_key']['url'] }}'|sed -r -n '/-----BEGIN PGP PUBLIC KEY BLOCK-----/,/-----END PGP PUBLIC KEY BLOCK-----/p'|sed -r 's/^.*(-----BEGIN PGP PUBLIC KEY BLOCK-----)/\\1/;s/(-----END PGP PUBLIC KEY BLOCK-----).*$/\\1/' > '{{ awscli['gpg_key']['storage']['raw'] }}'"

    - name: Get AWS cli gpg key hash
      stat:
        path: "{{ awscli['gpg_key']['storage']['raw'] }}"
        get_checksum: yes
        checksum_algorithm: sha512
      register: aws_cli_gpg_key_hash

    - name: Verify AWS cli gpg key hash
      when: aws_cli_gpg_key_hash.stat.checksum != awscli['gpg_key']['hash']['sha512']
      fail:
        msg: AWS cli gpg key hash doesnt match the expected hash

    - name: Build AWS cli gpg keyring
      command: "gpg --no-default-keyring --keyring '{{ awscli['gpg_key']['storage']['keyring'] }}' --import '{{ awscli['gpg_key']['storage']['raw'] }}'"


    - name: Download AWS cli archive gpg signature
      get_url:
         url:  "{{ awscli['archive']['signature'] }}"
         dest: "{{ awscli['storage']['prefix'] }}/awscli.zip.sig"
      register: aws_cli_archive_sig

    - name: Download AWS cli archive
      get_url:
         url:  "{{ awscli['archive']['url'] }}"
         dest: "{{ awscli['storage']['prefix'] }}/awscli.zip"
      register: aws_cli_archive

    - name: Check AWS cli archive gpg signature
      command: "gpg --no-default-keyring --keyring '{{ awscli['gpg_key']['storage']['keyring'] }}' --verify '{{ awscli['storage']['prefix'] }}/awscli.zip.sig' '{{ awscli['storage']['prefix'] }}/awscli.zip'"

    - name: Extract AWS cli from archive
      unarchive:
        src: "{{ awscli['storage']['prefix'] }}/awscli.zip"
        dest: "{{ awscli['storage']['prefix'] }}/"

    - name: Install AWS cli
      command:
        cmd: ./aws/install
        chdir: "{{ awscli['storage']['prefix'] }}/"


- name: Setup AWS cli aliases
  blockinfile:
    path: "/home/{{ primary_username }}/.bash_aliases"
    marker: "# {mark} AWS"
    create: yes
    owner: "{{ primary_username }}"
    group: "{{ primary_username }}"
    mode: u=rw,go=r
    block: |
      alias a=aws

- name: Setup AWS cli completers
  blockinfile:
    dest: "/home/{{ primary_username }}/.bashrc"
    marker: "# {mark} AWS Completer"
    block: |
      complete -C '/usr/local/bin/aws_completer' aws
      complete -C '/usr/local/bin/aws_completer' a

- name: Install cfn-flip
  pip:
    state: present
    executable: pip3
    name: cfn-flip
