- name: Install exa
  become: true
  become_user: "{{ primary_username }}"
  command: "'/home/{{ primary_username }}/.cargo/bin/cargo' install exa"
  args:
    creates: "/home/{{ primary_username }}/.cargo/bin/exa"
