- name: Setup gcd command alias
  blockinfile:
    path: "/home/{{ primary_username }}/.bash_aliases"
    marker: "# {mark} gcd"
    create: yes
    owner: "{{ primary_username }}"
    group: "{{ primary_username }}"
    mode: u=rw,go=r
    block: |
      function _gcd { CDPATH=/home/{{ primary_username }}/git/ _simpler_cd_completer "$@"; }
      complete -o nospace -F _gcd gcd
      function gcd { cd "/home/{{ primary_username }}/git/$1"; }
