- name: Install the Slack yum repository key
  rpm_key:
    state: present
    key: https://packagecloud.io/slacktechnologies/slack/gpgkey

- name: Install the Slack yum repository
  yum_repository:
    name: Slack
    description: Slack Repo
    baseurl: 'https://packagecloud.io/slacktechnologies/slack/el/7/$basearch'
    gpgcheck: no
    repo_gpgcheck: yes
    gpgkey: https://packagecloud.io/slacktechnologies/slack/gpgkey

- name: Install Slack
  yum:
    state: present
    name: slack
