- name: Install the Slack yum repository key
  rpm_key:
    state: present
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey

- name: Install the Slack yum repository
  yum_repository:
    name: Slack
    baseurl: 'https://packagecloud.io/slacktechnologies/slack/el/7/$basearch'
    gpgcheck: no
    repo_gpgcheck: yes
    gpgkey: https://packagecloud.io/slacktechnologies/slack/gpgkey

- name: Install Slack
  dnf:
    state: present
    name: slack
