- name: Kick off TLP
  command: tlp start

- name: Kick off Powertop
  command: powertop --auto-tune

- name: Disable powersaving for human interface devices
  shell: |
    HIDDEVICES="$(ls /sys/bus/usb/drivers/usbhid | grep -oE '^[0-9]+-[0-9\.]+' | sort -u)"
    for i in $HIDDEVICES; do
      echo -n "Enabling " | cat - "/sys/bus/usb/devices/$i/product"
      echo on > "/sys/bus/usb/devices/$i/power/control"
    done
