- name: Install Starship
  become: true
  become_user: "{{ primary_username }}"
  command: "'/home/{{ primary_username }}/.cargo/bin/cargo' install starship"
  args:
    creates: "/home/{{ primary_username }}/.cargo/bin/starship"

- name: Install Starship config
  copy:
    dest: "/home/{{ primary_username }}/.config/starship.toml"
    owner: "{{ primary_username }}"
    group: "{{ primary_username }}"
    mode: u=rwx,g=rx,o=
    content: |
      add_newline = false

      # Moved directory to second last (from default order)
      prompt_order = [
        "username",
        "hostname",
        "singularity",
        "kubernetes",
        "git_branch",
        "git_commit",
        "git_state",
        "git_status",
        "hg_branch",
        "docker_context",
        "package",
        "dotnet",
        "elixir",
        "elm",
        "erlang",
        "golang",
        "haskell",
        "java",
        "julia",
        "nim",
        "nodejs",
        "ocaml",
        "php",
        "purescript",
        "python",
        "ruby",
        "rust",
        "terraform",
        "zig",
        "nix_shell",
        "conda",
        "memory_usage",
        "aws",
        "env_var",
        "crystal",
        "cmd_duration",
        "custom",
        "line_break",
        "jobs",
        "battery",
        "time",
        "directory",
        "character",
      ]

      [line_break]
      disabled = true

      [character]
      use_symbol_for_status = true
      [directory]
      prefix = ""
      suffix = ""
      [cmd_duration]
      symbol = "⏱️ "
      prefix = ""

      [aws.region_aliases]
      ap-southeast-2 = "au"

      [git_branch]
      symbol = "🌱"
      prefix = ""
      [git_state]
      cherry_pick = "🍒"
      [docker_context]
      symbol = "🐋"
      prefix = ""
      [package]
      symbol = "📦"
      prefix = ""

      [aws]
      symbol = "☁️ "
      prefix = ""

      [python]
      symbol = "🐍"
      prefix = ""
      [rust]
      symbol = "🦀"
      prefix = ""
      [go]
      symbol = "🐹"
      prefix = ""
      [terraform]
      symbol = "💠"
      prefix = ""

      [memory_usage]
      disabled = false
      symbol = "🐏"
      prefix = ""
      show_percentage = true
      separator = "|"

- name: Setup Starship Terminal Prompt
  blockinfile:
    path: "/home/{{ primary_username }}/.bashrc"
    insertafter: "# END Rust"
    marker: "# {mark} Starship"
    block: |
      eval "$(starship init bash)"
      function _pre_starship_prompt_commands {
        local STATUS=$?  # Passthrough the last exit code for starship
        history -a
        __vte_prompt_command
        return $STATUS
      }
      PROMPT_COMMAND="_pre_starship_prompt_commands;starship_precmd"
