- name: Install Starship
  become: true
  become_user: "{{ primary_username }}"
  command: "'/home/{{ primary_username }}/.cargo/bin/cargo' install starship"
  args:
    creates: "/home/{{ primary_username }}/.cargo/bin/starship"

- name: Install Starship config
  copy:
    dest: "/home/{{ primary_username }}/.config/starship.toml"
    owner: "{{ primary_username }}"
    group: "{{ primary_username }}"
    mode: u=rwx,g=rx,o=
    content: |
      add_newline = false
      [line_break]
      disabled = true

      [character]
      use_symbol_for_status = true

      [aws.region_aliases]
      ap-southeast-2 = "au"

      [git_branch]
      symbol = "🌱"
      [git_state]
      cherry_pick = "🍒"
      [docker_context]
      symbol = "🐋"
      [package]
      symbol = "📦"

      [aws]
      symbol = "☁️ "

      [python]
      symbol = "🐍"
      [rust]
      symbol = "🦀"
      [go]
      symbol = "🐹"
      [terraform]
      symbol = "💠"

- name: Setup Starship Terminal Prompt
  blockinfile:
    path: "/home/{{ primary_username }}/.bashrc"
    insertafter: "# END Rust"
    marker: "# {mark} Starship"
    block: |
      eval "$(starship init bash)"
      function _pre_starship_prompt_commands {
        local STATUS=$?  # Passthrough the last exit code for starship
        history -a
        __vte_prompt_command
        return $STATUS
      }
      PROMPT_COMMAND="_pre_starship_prompt_commands;starship_precmd"
