- name: Create a .secrets folder
  file:
    state: directory
    path: "/home/{{ primary_username }}/.secrets/"
    owner: "{{ primary_username }}"
    group: "{{ primary_username }}"
    mode: u=rwx,g=s,o=

- name: Limit home folder access
  file:
    state: directory
    path: "/home/{{ primary_username }}/"
    owner: "{{ primary_username }}"
    group: "{{ primary_username }}"
    mode: u=rwx,g=rx,o=
