- name: Install fd
  become: true
  become_user: "{{ primary_username }}"
  command: "'/home/{{ primary_username }}/.cargo/bin/cargo' install fd-find"
  args:
    creates: "/home/{{ primary_username }}/.cargo/bin/fd"
